[package]
name = "mdanalytics"
version = "0.1.0"
edition = "2024"

[dependencies]
influxdb = { version = "0.7.2", features = ["derive"] }
plotters = "0.3.7"
polars = { version = "0.52.0", features = ["lazy", "csv", "serde"] }
